# Generated by Django 4.2.2 on 2023-06-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='choices',
            field=models.CharField(choices=[('P', 'Publish'), ('D', 'Draft')], max_length=10, null=True),
        ),
    ]
