# Generated by Django 4.2.2 on 2023-06-28 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_remove_post_choices_post_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='categories',
            new_name='category',
        ),
    ]
