# Generated by Django 4.2.1 on 2023-06-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0005_rename_categories_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='myfile',
            field=models.FileField(null=True, upload_to='images/post'),
        ),
    ]
