# Generated by Django 4.2.1 on 2023-07-02 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0007_newpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewPost',
        ),
    ]
