# Generated by Django 4.2.1 on 2023-07-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0008_delete_newpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='num_of_clicks',
            field=models.IntegerField(default=0),
        ),
    ]
